Proj_1/Proj_1/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'register/',register_view, name='register'),
    url(r'login/',login_view, name='login'),
    url(r'logout/',logout_view, name='logout'),
    url(r'shop/',include("shop.urls", namespace='shop')),
    url(r'^', include("work_posts.urls")),
    # this includes the urls file under the work_post folder, but only the part after "posts/"
    # in work_posts.urls you will only see the remaining part so posts/delete is split and routed
    ]

if settings.DEBUG:      # ensures that this will only be done in DEV
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    url(r'robot/', include('work_posts.robot_urls')),

    ]

Proj_1/shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import shop_list, shop_detail, shop_create


urlpatterns = [
    url(r'^$', shop_list, name='shop_list'),
    url(r'^create/$', shop_create, name='shop_create'),
    url(r'^(?P<id>\d+)/$', shop_detail, name='shop_edit'),
    #url(r'^(?P<id>\d+)/$', item_detail, name='edit'),
]

Proj_1/comments/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class CommentManager(models.Manager):
    def all(self): # this should give all the comments and not the replies
        qs = super(CommentManager, self).filter(parent=None)
        return qs

    def filter_by_instance(self, instance):
        # now no need to specify the model since the instance belongs to a model
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
        return qs


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    # post = models.ForeignKey(Post) #this makes the relation to the posts model, what if it is not related to a post?
    # above now removed to replace with the generic stuff
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = models.ForeignKey('self', null=True, blank=True)

    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    objects = CommentManager()

    class Meta:
        ordering = ['-timestamp']


    def __str__(self):
        label = self.user.username + ' - ' + self.content[:30]
        return str(label)

    def get_absolute_url(self):
        return reverse("comments:thread", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("comments:delete", kwargs={"id": self.id})

    def children(self):
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        else:
            return True

Proj_1/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block head_title %}Our Posting{% endblock head_title%}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href='{% static "css/base.css" %}'/>
    <!--this link method is subject to the directory name not changing
       <link rel="stylesheet" href="'/static/css/base.css" />, the above makes it dynamic-->
    <!--   -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        {% block style %}
        {% endblock style %}
    </style>
    {% block head_extra %}{% endblock head_extra %}
</head>
    <body>
        <div id="fb-root"></div>
        <!-- <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.3"></script>-->

        {% include "messages_display.html" %}
        <div class="container">
            <nav aria-label="breadcrumb">
                <ul class="nav nav-pills nav-fill">
                    <li class="nav-item">
                        <a class="nav-link" href="">Home</a>
                    </li>
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create' %}">Post New</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% endif %}

                </ul>
            </nav>
        </div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-10">
                    {% block content %} {% endblock content%}
                </div>
            </div>
        </div>



        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.2/marked.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".content-markdown").each(function(){
                var content = $(this).text()
               // console.log("Original content now ---")
               // console.log(content)
                var markedContent = marked(content)
                console.log("Marked up version ---------")
                console.log(markedContent)
                $(this).html(markedContent)
            })
             $(".content-markdown img").each(function(){
                //this will add the class tag to all images to make it respond to the bootstrap setup
                // i don't actually use it due to the card deck
                //$(this).addClass("img-responsive")
            })

            $(".comment-reply-btn").click(function(event){
                //alert("reply button clicked");
                event.preventDefault();
                /*if ($(this).parent().next(".comment-reply").length > 0){
                    alert ("found it");
                }else{
                     alert ("Not found it");
                }*/
                $(this).parent().next(".comment-reply").fadeToggle();
            })
        })
    </script>
    </body>
</html>

Proj_1/templates/comment_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlify %}
{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title%}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h1>Confirm delete</h1>
    <form method="POST" action="." >{% csrf_token %}
        <p>Are you sure you want to delete {{ object }}?</p>
        <p>{{ object.id }}</p>
        <input type="hidden" name="id" value="{{ object.id }}">
        <input type="submit" value="Delete" class="btn btn-warning">
        <a href='{{ object.get_absolute_url }}' class="btn btn-secondary">Cancel</a>
    </form>
    <hr/>

</div>
{% endblock content%}

Proj_1/templates/index.html
<!DOCTYPE html><!-- -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is our template start</title>
</head>
<body>
    Some funky stuff showing here!
    <h4>{{ title }}</h4>
    {% if object_list %}
        <ul>
        {% for obj in object_list%}
            <li><!-- this one needed because at the time i still have ..posts/detail as the url pattern-->
                <!--Post Made : <a href="/posts/detail/{{ obj.id }}/">{{ obj.title }}</a><br/>
                 the one below now uses the url reverse
                 a further iimprovement on : <a href='{% url "detail" id=obj.id %}'>{{ obj.title }}</a>
                 -->
                Post Made : <a href='{{ obj.get_absolute_url }}'>{{ obj.id }} {{ obj.title }}</a><br/>
                On : {{ obj.create_date }}<br/>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>
            Post Made :{{ obj.id }} {{ obj.title }}<br/>
            Post Content : {{ obj.content }}<br/>
            On : {{ obj.create_date }}<br/>
            Updated: {{ obj.update_date }}<br/>
        </p>
    {% endif %}
</body>
</html>

Proj_1/templates/item_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlify %}
{% block head_title %}
    Add item
{% endblock head_title%}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">

<h2>{{title}}</h2>
    <a href="{% url 'shop:shop_list' %}" class="top-menu">Back to list</a><br>
    <p class="font-italic">{% if notice %}{{ notice }}{% endif %}</p>

    <form method='POST' action="" >
        {% csrf_token %}
        {{ form|crispy }}
        <input type='submit' class="btn btn-secondary" name="add_one" value = 'Add one to list'/>
        <input type='submit' class="btn btn-secondary" name="add_more" value = 'Add several to list'/>
    </form>

</div>
{% endblock content%}

Proj_1/templates/item_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlify %}
{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title%}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">

<h2>Item detail</h2>
    <p>
        Number {{ instance.id }} : {{ instance.description }}<br/>

        Requested on: {{ instance.date_requested }}<br/>


    </p><hr/>
    Request by:
    {% if instance.requested.get_full_name %}
        {{ instance.requested.get_full_name }}
    {% else %}
        {{ instance.requested.name }}
    {% endif %}
    <hr/>


</div>
{% endblock content%}

Proj_1/templates/item_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h1>{{ title }}</h1>
<a href="{% url 'shop:shop_create' %}" class="top-menu">Add item</a><br>
<p class="font-italic">{% if notice %}{{ notice }}{% endif %}</p>
{% if object_list%}

    {% for obj in object_list %}
    <form method="POST" action="." >{% csrf_token %}
        {{ form|crispy }}
        <div class="row p-1 mb-2 bg-light text-dark">
            <div class="col-md-8 col-xs-8">{{ obj.id }}. {{ obj.description }}</div>
            <div class="col-md-4 col-xs-4">
                <input type="submit" name="got_item|{{ obj.id }}" value="Purchased" class="btn btn-success btn-sm">
                <input type="submit" name="cancel_item|{{ obj.id }}" value="Cancel" class="btn btn-outline-danger btn-sm">
                <small>Req'd: {{ obj.date_requested | date:"d M"}} ({{ obj.requested.get_full_name }})</small></div>
        </div>
    </form>
    {% endfor %}

{% else %}
    <p>No list yet!</p>
{% endif %}

    <!--
    <div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ contacts.previous_page_number }}{% if request.Get.g %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.Get.g %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
    </div>
-->

{% endblock content%}

Proj_1/templates/login_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h2>Site {{ title }}</h2>

    <form method='POST' action="" >
        {% csrf_token %}
        {{ form|crispy }}
        <input type='submit' class="btn btn-secondary" value = {{ title }}>

    </form>
</div>
{% endblock content%}

Proj_1/templates/messages_display.html
{% if messages %}
    <div class='messages'>
        <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
            </li>
        {% endfor %}
        </ul>

    </div>
{% endif %}

Proj_1/templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlify %}
{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title%}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">

<h2>Post detail</h2>
    <p>
        {% if instance.image %}
            <img src="{{ instance.image.url }}" class="img-responsive img-thumbnail" /><br/>
        {% endif %}
        Number {{ instance.id }} : {{ instance.title }}<br/>
        Status =
        {% if instance.draft %}
            <span style="color:red;">Draft</span>
        {% else %}
            Published
        {% endif %}
        <br><hr/>
        {{ instance.get_markdown | truncatewords_html:8 }}
        <small class="text-muted"> On : {{ instance.create_date }}<br/>
            Updated: {{ instance.update_date }}<br/>
            Read: {{instance.read_time}} minute{% if instance.read_time > 1 %}s{% endif %}<br/>
        </small>

    </p><hr/>
    {% if instance.user.get_full_name %}
        <p>Author: {{ instance.user.get_full_name }}</p>
    {% else %}
        <p>{{ instance.user.name }}</p>
    {% endif %}
    <hr/>
    {# request.build_absolute_uri #}
    {# share_string #}Share string:
    {{ instance.content|truncatechars:20|urlify }}<br/>

    <!--Comments as property: see RA version-->

    <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
        <span class="fb-comments-count" data-href="{{ request.build_absolute_uri }}"></span>
    <div>
        <hr/>
        <p class="lead"><h3>Comments</h3></p>
        {% if request.user.is_authenticated %}
        <form method="POST" action="." >{% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Post comment" class="btn btn-secondary">
        </form>
        {% else %}
        <p>You must log in to comment</p>
        {% endif %}
        {% for comment in comments %}
            <blockquote class="blockquote">
                <p class="mb-0">{{ comment.content }} </p>
                <footer class="blockquote-footer"> {{ comment.id }} {{ comment.user }}, {{comment.timestamp|timesince }} ago. |
                    {{ comment.children.count}} Comment{% if comment.children.count > 0 %}s{% endif %}
                <a class="comment-reply-btn" href="#">Reply  </a><a href="{{ comment.get_absolute_url }}">Thread</a> </footer>
                <!--second form inside for the replied to comments , used this class before col-md-12 offset-md--->
                <div class="comment-reply" >
                    {% for child_comment in comment.children %}
                        <blockquote>
                            <p>{{ child_comment.content }}</p>
                            <footer class="blockquote-footer">{{ child_comment.id }} via {{ child_comment.user }} |
                                {{child_comment.timestamp|timesince }} ago</footer>
                        </blockquote>
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                        <form method="POST" action="." >{% csrf_token %}
                            {{ form|crispy }}
                            <input type="hidden" name="parent_id" value="{{ comment.id }}">
                            <input type="submit" value="Reply" class="btn btn-secondary">
                        </form>
                    {% else %}
                        <p>You must log in to comment</p>
                    {% endif %}
                </div>
            </blockquote><hr/>
        {% endfor %}

    </div>
    <hr/>

    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}"> Facebook </a>
    <a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify  }}%20{{ request.build_absolute_uri }}">
         Twitter</a>
    <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&
        title={{ instance.title }}%20&summary={{ instance.content|truncatechars:80|urlify  }}%20&source={{ request.build_absolute_uri }}">
         Linkedin</a>
</div>
{% endblock content%}

Proj_1/templates/post_detail_RA.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlify %}
{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title%}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">

<h2>Our Post detail form</h2>
    <p>
        This is the Post_detail page<br/>
        {% if instance.image %}
            <img src="{{ instance.image.url }}" class="img-responsive img-thumbnail" /><br/>
        {% endif %}
        Post Made :{{ instance.id }} {{ instance.title }}<br/>
        Status =
        {% if instance.draft %}
        <span style="color:red;">Draft</span>
        {% else %}
        Published
        {% endif %}
        <br><hr/>

        <!-- <div class="content-markdown"> now disabled due to the server operation of the markdown-->
        <!--    Post Content : {{ instance.content }}<br/> -->
            {{ instance.get_markdown | truncatewords_html:8 }}
            On : {{ instance.create_date }}<br/>
            Updated: {{ instance.update_date }}<br/>
       <!--  </div> -->
    </p><hr/>
    {% if instance.user.get_full_name %}
        <p>Author: {{ instance.user.get_full_name }}</p>
    {% else %}
        <p>{{ instance.user.name }}</p>
    {% endif %}
    <hr/>
    {# request.build_absolute_uri #}
    {# share_string #}Share string:
    {{ instance.content|truncatechars:20|urlify }}<br/>

    Comments as property:
    <br/>
    {{ instance.comments.all }}
    <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
        <span class="fb-comments-count" data-href="{{ request.build_absolute_uri }}"></span>
    <div>
        <hr/>
        <!--{{ instance.comment_set.all }} only workes when there is a direct relationship between comments and posts-->
        <p class="lead">Comments</p>
        {% for comment in comments %}
            <blockquote>
                <p>{{ comment.content }} </p>
                <footer>By {{ comment.user }}, {{comment.timestamp|timesince }} ago.</footer>
            </blockquote><hr/>
        {% endfor %}
    </div>
 <!--   <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-width="85%" data-numposts="5"></div> -->
    <hr/>

    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}"> Facebook </a>
    <a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify  }}%20{{ request.build_absolute_uri }}">
         Twitter
    </a>
    <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&
        title={{ instance.title }}%20&summary={{ instance.content|truncatechars:80|urlify  }}%20&source={{ request.build_absolute_uri }}">
         Linkedin
    </a>
</div>
{% endblock content%}

Proj_1/templates/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_extra %}
{{  form.media }} {# the object needed to bring the css content into the  template#}
{% endblock head_extra %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h2>Our Post form</h2>

    <form method='POST' action="" enctype="multipart/form-data">
        <!--With no defined method it defaults to Get that only adds it to the URL . Action defined the destination. the enctype required for data transfer-->
        <!--also require changes to the views to pass the data -->
        {% csrf_token %}
        We'll do some posts...Add it below, will ya?
        {{ form|crispy }}
        {% if instance.title %}
        <input type='submit' class="btn btn-secondary" value = 'Update Post'/>
        {% else %}
        <input type='submit' class="btn btn-secondary" value = 'Create Post'/>
        {% endif %}
    </form>
</div>
{% endblock content%}

Proj_1/templates/post_list.html
{% extends "base.html" %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h1>Our Post List</h1>
<br/>
<form method="GET" action="">
    <div class="input-group">
        <!--<input type="text" name="q" placeholder="Search posts" value="{{ request.GET.q }}"/> -->
        <input class="form-control" type="text" name="q" placeholder="Search posts" value="{{ request.GET.q}} ">
        <span class="input-group-btn">
            <!--<input class="btn btn-secondary" type="submit" value="Search"/>-->
            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i> </button>
        </span>
    </div>
</form><br/>

<div class="card-deck">
    <div class="col-sm-12">
{% for obj in object_list %}

        <div class="card" style="max-width: 400px;">
           {% if obj.image %} <img src="{{ obj.image.url }}" class="card-img-top" >{% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ obj.id }}. {{ obj.title }}</h5>
        <!-- <p class="card-text">{{ obj.content|linebreaks|truncatechars:120 }}</p>   removed in favour of the serverside method -->
        <p class="card-text">{{ obj.get_markdown }}</p>
        <p> <a href='{{ obj.get_absolute_url }}' class = 'btn btn-primary' role='button'>View</a>   </p>
         <div class="card-footer text-muted">
            {% if obj.user.get_full_name %}
                <p>Author: {{ obj.user.get_full_name }}</p>
            {% else %}
                <p>{{ obj.user.name }}</p>
            {% endif %}
             Status =
            {% if obj.draft %}
            <span style="color:red;">Draft</span>
            {% else %}
            Published
            {% endif %}<br/>
             <small>    Updated: {{ obj.update_date|timesince }} ago</small>
        </div>
        </div></div>
        <div class="mt-3" /></div>
<!--{% cycle "" "</div><div class='row'>" %}  if you want to ensure there is a break after each group this will insert the extra row class-->
    <!-- -->

{% endfor %}
</div>
    <div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ contacts.previous_page_number }}{% if request.Get.g %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.Get.g %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
    </div>

</div>
{% endblock content%}

Proj_1/templates/robot_form.html
{% extends 'base.html' %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h2>Our Robot form</h2>

    <form method='POST' action="" enctype="multipart/form-data">
        {% csrf_token %}
        Add a new Robot's details below<br/>

        {{ form.as_p }}
        {% if instance.title %}
        <input type='submit' class="btn btn-secondary" value = 'Update Robot'/>
        {% else %}
        <input type='submit' class="btn btn-secondary" value = 'Create Robot'/>
        {% endif %}
    </form>
</div>
{% endblock content%}

Proj_1/templates/robot_list.html
{% extends "base.html" %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h1>Our Robot fleet</h1>

<div class="card-deck">
    <div class="col-sm-12">
{% for obj in object_list %}

        <div class="card" style="max-width: 400px;">
           {% if obj.image %} <img src="{{ obj.image }}" class="card-img-top" >{% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ obj.id }}. {{ obj.name }}</h5>
        <p class="card-text">{{ obj.job|linebreaks|truncatechars:120 }}</p>
            <p> <a href='{{ obj.get_absolute_url }}' class = 'btn btn-primary' role='button'>View</a>   </p>

         <div class="card-footer text-muted">

         </div>
        </div></div>
        <div class="mt-3" /></div>
<!--{% cycle "" "</div><div class='row'>" %}  if you want to ensure there is a break after each group this will insert the extra row class-->
    <!-- -->
 <!--model content = name /number/job  <a href='{# obj.get_absolute_url #}'-->
{% endfor %}
</div>
    <div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ contacts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}">next</a>
        {% endif %}
    </span>
    </div>

</div>
{% endblock content%}